config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  resources :menu_items, only: [:index, :show], path: 'our-food'
  get '/our-vegetarian-food' => 'menu_items#vegetarian'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'


  mount Sidekiq::Web => '/sidekiq'
  namespace :admin do  #all routes inside this bloc will have a /admin in front of them.
    get '/' => 'base#index' #base controller could be called anything (except admin)

    resources :menu_items
    resources :locations
  end

end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include Indexable
  include PgSearch

  #pg_search_scope :search, against: [:street_address, :city, :state]
  multisearchable against: [:street_address, :city, :state]

  geocoded_by :address
  after_validation :geocode

  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true, reject_if: ->(emp_attrs) { emp_attrs['name'].blank? }

  after_initialize :add_employee

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  def name
    address
  end

  private

  def add_employee
    employees.build if employees.empty?
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end

end






# using: { tsearch: { prefix: true} }

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include Indexable
  include PgSearch
  multisearchable against: [:name, :description]

  # pg_search_scope :search, against: [:name, :description], associated_against: { ingredients: [:name] }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients

  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def ingredient_names
    ingredients.pluck(:name).join(', ')
  end

  def self.vegetarian
    where(vegetarian: true)
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:twitter]


  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'], uid: auth_hash['uid'])
    instance.save(validate: false)
    instance
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end

  def show
    @item = MenuItem.find(params[:id])
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user
      redirect_to root_path, notice: 'User now signed in with twitter'
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    # @menu_items = MenuItem.search(params[:q])
    # @locations = Location.search(params[:q])
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index

  end

  def about

  end

  def contact

  end

  def contact_submit
    # the line below is another way to do this using sidekiq's built in worker,
    #  so you don't have to create a custom worker, just add this line and you're done.
    # ContactMailer.delay.contact_request(params)
    ContactRequestWorker.perform_async(params[:name], [:email], [:subject], [:question])
    redirect_to root_path, notice: 'Thanks for contacting us!'
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tacoz</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script src="http://maps.google.com/maps/api/js?sensor=true?"></script>
</head>
<body>
  <div class="container">
    <header id="site-header">

      <div class="row">
        <div class="col-sm-4">
          <%= link_to(image_tag('logo.jpg'), root_path) %>
        </div>
        <div class="col-sm-8">
          <%= render('shared/topsearch') %>
          <br>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          <% else %>
            <%= link_to('Login with Twitter',  user_omniauth_authorize_path("twitter")) %>
          <% end %>
        </div>
      </div>

      <%= render('shared/topnav') %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>
    <section id="site-content">
      <%= yield %>
    </section>
    <footer id="site-footer">
      <p class="text-center">
        <small>copyright &copy; 2014 Tacoz</small>
      </p>
    </footer>
  </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <ul class="nav navbar-nav">
    <li><a href="<%= root_path %>">Home</a></li>
    <li><a href="<%= about_path %>">About</a></li>
    <li class="dropdown">
      <a href="<%= '#' %>" data-toggle="dropdown">Menu <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a href="<%= menu_items_path %>">All Items</a></li>
        <li><a href="<%= our_vegetarian_food_path %>">Vegetarian</a></li>
      </ul>
    </li>
    <li><a href="<%= locations_path %>">Locations</a></li>
    <li><a href="<%= contact_path %>">Contact</a></li>
  </ul>
</nav>

app/views/shared/_topsearch.html.erb
<%= form_tag(search_path, method: :get) do %>
  <div class="input-group">
    <%= text_field_tag(:q, '', placeholder: 'Search...', class: 'form-control') %>
    <span class="input-group-btn">
      <%= submit_tag('Go!', class: 'btn btn-primary') %>
    </span>
  </div>
<% end %>