config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  resources :menu_items, only: [:index, :show], path: 'our-food'
  get '/our-vegetarian-food' => 'menu_items#vegetarian'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'


  mount Sidekiq::Web => '/sidekiq'
  namespace :admin do  #all routes inside this bloc will have a /admin in front of them.
    get '/' => 'base#index' #base controller could be called anything (except admin)

    resources :menu_items
    resources :locations
  end

end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end

end

app/models/concerns/locatable.rb
module Locatable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      indexes :street_address
      indexes :city
      indexes :state
      indexes :coordinates, type: 'geo_point', lat_lon: true, normalize: false, validate: true
    end
  end

  module InstanceMethods
    def coordinates
      [latitude, longitude]
    end

    def as_indexed_json(options={})
      as_json(
        methods: [
          :coordinates,
          :address
        ]
      )
    end
  end

  module ClassMethods
    def search(params)
      es = __eslasticsearch__
      definition = {
        query: {
          query_string: {
            query: params[:q], default_operator: 'AND'
          }
        }
      }
      definition.merge!({
        filter: {
          and: {
            geo_distance: {
              distance: "#{params[:distance]}mi",
              coordinates: params[:coordinates]
            }
          }
        }
      })
      
      response = es.search(definition)
      response
    end
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include Indexable
  include PgSearch

  #pg_search_scope :search, against: [:street_address, :city, :state]
  multisearchable against: [:street_address, :city, :state]

  geocoded_by :address
  after_validation :geocode

  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true, reject_if: ->(emp_attrs) { emp_attrs['name'].blank? }

  after_initialize :add_employee

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  def name
    address
  end

  private

  def add_employee
    employees.build if employees.empty?
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end

end






# using: { tsearch: { prefix: true} }

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include Indexable
  include PgSearch
  multisearchable against: [:name, :description]

  # pg_search_scope :search, against: [:name, :description], associated_against: { ingredients: [:name] }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients

  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def ingredient_names
    ingredients.pluck(:name).join(', ')
  end

  def self.vegetarian
    where(vegetarian: true)
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:twitter]


  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'], uid: auth_hash['uid'])
    instance.save(validate: false)
    instance
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end

  def show
    @item = MenuItem.find(params[:id])
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user
      redirect_to root_path, notice: 'User now signed in with twitter'
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    # @menu_items = MenuItem.search(params[:q])
    # @locations = Location.search(params[:q])
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index

  end

  def about

  end

  def contact

  end

  def contact_submit
    # the line below is another way to do this using sidekiq's built in worker,
    #  so you don't have to create a custom worker, just add this line and you're done.
    # ContactMailer.delay.contact_request(params)
    ContactRequestWorker.perform_async(params[:name], [:email], [:subject], [:question])
    redirect_to root_path, notice: 'Thanks for contacting us!'
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/search_results/index.html.erb
<h1 class="page-header">Search Results for <%= params[:q] %></h1>

<% @results.each do |result| %>
  <%= link_to(result.name, result) %>
<% end %>

app/views/site/about.html.erb
<h1 class="page-header">About Tacoz</h1>
<p class="lead">
  Your tastebuds will become your best friends.
</p>
<div class="content">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum urna tellus. Ut commodo dolor vitae interdum molestie. Fusce porttitor, augue sit amet varius blandit, turpis arcu viverra metus, vel auctor nulla massa quis elit. Nam congue interdum nibh quis venenatis. Etiam sit amet nunc ut nisl lacinia posuere nec sed lorem. Proin tincidunt eget velit hendrerit rutrum. In sit amet elementum leo. Praesent pharetra nisl ut fermentum aliquet. Curabitur accumsan lectus nec scelerisque ornare. Quisque convallis ullamcorper dolor. Vestibulum quis mattis purus. Duis volutpat eget erat eu fermentum. Duis fermentum congue augue. Donec vel feugiat quam. 
</div>

app/views/site/contact.html.erb
<h1 class="page-header">Contact Us</h1>
<p class="lead">
  Just shoot us a note, and we'll get back to you when we can!
</p>
<%= form_tag(submit_contact_path, role: 'form', class: "form-horizontal") do %>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'Name') %>
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <%= text_field_tag(:email, '', class: 'form-control', placeholder: 'Email') %>
    </div>
  </div>
  <div class="form-group">
    <label for="Subject" class="col-sm-2 control-label">Subject</label>
    <div class="col-sm-10">
      <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'Subject') %>
    </div>
  </div>
  <div class="form-group">
    <label for="question" class="col-sm-2 control-label">Question</label>
    <div class="col-sm-10">
      <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'Question') %>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag('Send', class: 'btn btn-info btn-lg') %>
    </div>
  </div>
<% end %>